# This is a basic workflow to help you get started with Actions

name: Refresh branch status

# Controls when the workflow will run
on:
  push:
    branches: [ branch-status, main ] # TODO: remove main, just for ease of testing

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  check-branch:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Validate destination branch status
        uses: ./eng/actions/refresh-branch-status
        id: refresh
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
